version: '3.2'

services:
  microcontent-toolkit:
    image: ghcr.io/microcontent/microcontenttoolkit-2:main
    networks:
      - web
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9010:9010"
      - "9011:9011"
      - "9012:9012"
      - "9013:9013"


networks:
  web: